
name: CI-CD
'on':
  push:

jobs:
  cog:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cog
        run: |
            sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
            sudo chmod +x /usr/local/bin/cog
            cog build
