
name: CI-CD
'on':
  push:

jobs:

    cog:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cog
        run: |
            sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
            sudo chmod +x /usr/local/bin/cog
            cog build
     
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: zerefdragoneel
#           password: dckr_pat_d7WAHZzJqnMnSI8donK8ALVCrZk
#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           push: true
#           tags: user/app:latest
